# Task 01

In [8]:
import numpy as np
arr1 = np.arange(1,21)
arr_2d = arr1.reshape(4,5)
arr_2d[:,-1] = 0
arr_flat = arr_2d.flatten()
print(arr_flat)

[ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


# Task 02

In [47]:
import numpy as np
import random

arr_2d = np.random.randint(10,50,size=(5,5))
# columnwise
col_mean = np.mean(arr_2d,axis=1)
col_sum = np.sum(arr_2d,axis=1)
col_mini = np.min(arr_2d,axis=1)
col_maxi = np.max(arr_2d,axis=1)

print("Mean: ",col_mean)
print("Sum: ",col_sum)
print("Minimum: ",col_mini)
print("Maximum: ",col_maxi)

# rowwise

row_mean = np.mean(arr_2d,axis=0)
row_sum = np.sum(arr_2d,axis=0)
row_mini = np.min(arr_2d,axis=0)
row_maxi = np.max(arr_2d,axis=0)
print()
print("Mean: ",col_mean)
print("Sum: ",col_sum)
print("Minimum: ",col_mini)
print("Maximum: ",col_maxi)


Mean:  [29.8 34.4 30.  29.6 22.2]
Sum:  [149 172 150 148 111]
Minimum:  [17 16 10 15 12]
Maximum:  [49 48 49 44 43]

Mean:  [29.8 34.4 30.  29.6 22.2]
Sum:  [149 172 150 148 111]
Minimum:  [17 16 10 15 12]
Maximum:  [49 48 49 44 43]


# Task 03

In [31]:
import numpy as np
mat = np.identity(4)
np.fill_diagonal(mat,np.diagonal(mat)+5)
mat[-1] =1
print(mat)


[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


# Task 04

In [46]:
import numpy as np
import random
arr_1d = np.random.randint(0,20,size = 15)
print(arr_1d)
print()
unique,counts = np.unique(arr_1d,return_counts = True)
print("Unique: ",unique)
print("Counts: ",counts)
# print(dict(zip(unique_counts)))
indices = np.where(arr_1d>10)[0]
print("\nIndices of Elements >10:")
print(indices)

[12 12  4 10  1  3  9 14  5  5 15  2  0  4  9]

Unique:  [ 0  1  2  3  4  5  9 10 12 14 15]
Counts:  [1 1 1 1 2 2 2 1 2 1 1]

Indices of Elements >10:
[ 0  1  7 10]


# Task 05

In [30]:
import numpy as np
import random

arr = np.random.rand(3,4)
arr = np.round(arr,2)
arr[:,1] = 0.5
print(arr)

[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]
